#!/usr/bin/env sh
#
# Summary: List installed packages
# Usage: shsh list [-d|--details]
#
# Options:
#   -d, --details    display the URL of the repository

set -e
# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

case $1 in
  -d|--details)
    show_details="true"
    shift
  ;;
esac

if [ "$#" -gt 0 ]; then
  shsh-help list
  exit 1
fi

for package_path in "${SHSH_PACKAGES_PATH}"/*/*; do
  [ -e "$package_path" ] || [ -L "$package_path" ] || continue

  username="$(dirname "$package_path")"
  username="${username##*/}"
  package="${package_path##*/}"
  if [ -z "$show_details" ]; then
    echo "$username/$package"
  else
    if [ -L "$package_path" ]; then
      # is a locally linked folder
      extra_info="$(resolve_link "$package_path")"
    else
      # is a git with remote upstream
      extra_info="$(git --git-dir="$package_path/".git config --get remote.origin.url)"
    fi
    printf "%-30s %-30s\n" "$username/$package" "($extra_info)"
  fi
done
