#!/usr/bin/env sh

package="$1"

if [ -e "$SHSH_PACKAGES_PATH/$package/package.sh" ]; then
  # shellcheck source=/dev/null
  . "$SHSH_PACKAGES_PATH/$package/package.sh"
  bins=$(echo "${BINS:-}" | tr ':' '\n')
fi

if [ -z "$bins" ]; then
  list_all_executable() {
    cd "$1" && find "$2" -maxdepth 1 -mindepth 1 -perm -u+x -type f -or -type l
  }
  if [ -e "$SHSH_PACKAGES_PATH/$package/bin" ]; then
    bins=$(list_all_executable "$SHSH_PACKAGES_PATH/$package" bin)
  else
    # remove the "./" prefix with cut
    bins=$(list_all_executable "$SHSH_PACKAGES_PATH/$package" "." | cut -sd / -f 2-)
  fi
fi

IFS='
'
for bin in $bins; do
  name="${bin##*/}"
  if ${REMOVE_EXTENSION:-false}; then
    name="${name%%.*}"
  fi
  mkdir -p "$SHSH_INSTALL_BIN"
  ln -s "$SHSH_PACKAGES_PATH/$package/$bin" "$SHSH_INSTALL_BIN/$name"
  # chmod +x "$SHSH_INSTALL_BIN/$name"
done
