#!/usr/bin/env sh

set -e

. "${UTILS_FUNC:?}"

package="$1"

echo_if_verbose "> Starting to unlink completions..."
remove_linked "$SHSH_PACKAGES_PATH/$package" "$SHSH_PREFIX/completions/bash/"*
remove_linked "$SHSH_PACKAGES_PATH/$package" "$SHSH_PREFIX/completions/zsh/compsys/"*
remove_linked "$SHSH_PACKAGES_PATH/$package" "$SHSH_PREFIX/completions/zsh/compctl/"*
remove_linked "$SHSH_PACKAGES_PATH/$package" "$SHSH_PREFIX/completions/fish/"*
