#!/usr/bin/env sh

set -e

# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

target_folder="$(get_operation_root "$SHSH_PACKAGES_PATH/$1")"

echo_if_verbose "> Starting to link man..."

link_mans() {
  file="$1"
  is_file_or_link "$file" || return 0

  case "$file" in
    *.[1-9])
      # get the last digit
      n="${file##*[!0-9]}"
      ;;
    *.[1-9].gz)
      # remove suffix with dot (i.e. gz)
      _file="${file%.*}"
      # get the last digit
      n="${_file##*[!0-9]}"
      ;;
    *)
      return
      ;;
  esac
  manfile=$(basename "$file")
  mkdir -p "${SHSH_INSTALL_MAN}/man${n}"

  src="$file"
  target="$SHSH_INSTALL_MAN/man${n}/$manfile"
  add_link "$src" "$target"
}

if [ -n "${MANS_ROOT}" ]; then
  for file in "$target_folder/$MANS_ROOT"/* "$target_folder/$MANS_ROOT"/*/*; do
    link_mans "$file"
  done
elif [ -z "${MANS+x}" ]; then
  # man can be in package root or in a subdir named 'man'
  ##### the following brace expansion is not supported in POSIX
  # "$target_folder"/{,auto}{complete,completion}{,s}{,/fish}/*.fish
  for file in \
    "$target_folder"/*                \
    "$target_folder"/man/man*/*       \
    "$target_folder"/share/man/man*/* \
    "$target_folder"/man/*            \
    "$target_folder"/doc/*            \
    "$target_folder"/docs/*           \
    "$target_folder"/share/man/*      \
    "$target_folder"/share/doc/*      \
    "$target_folder"/share/docs/*
  do
    link_mans "$file"
  done
else
  IFS=:
  for file in $MANS; do
    link_mans "$file"
  done
fi
