#!/usr/bin/env sh

set -e
# shellcheck disable=SC2153  # no misspelling

# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

target_folder="$(get_operation_root "$SHSH_PACKAGES_PATH/$1")"

echo_if_verbose "> Starting to link completions..."
if [ -e "$target_folder/package.sh" ]; then
  # shellcheck source=/dev/null
  . "$target_folder/package.sh"
fi

IFS=:
if [ -n "${BASH_COMPLETIONS:=}" ]; then
  mkdir -p "$SHSH_PREFIX/completions/bash"
  for completion in $BASH_COMPLETIONS; do
    ln -s "$target_folder/$completion" "$SHSH_PREFIX/completions/bash/${completion##*/}"
  done
fi

if [ -n "${ZSH_COMPLETIONS:=}" ]; then
  mkdir -p "$SHSH_PREFIX/completions/zsh/compsys"
  mkdir -p "$SHSH_PREFIX/completions/zsh/compctl"
  for completion in $ZSH_COMPLETIONS; do
    src="$target_folder/$completion"
    if grep -q "#compdef" "$src"; then
      target="$SHSH_PREFIX/completions/zsh/compsys/${completion##*/}"
    else
      target="$SHSH_PREFIX/completions/zsh/compctl/${completion##*/}"
    fi
    add_link "$src" "$target"
  done
fi

link_fish_completion_file() {
  src="$1"
  target="$SHSH_PREFIX/completions/fish/"
  mkdir -p "$target"

  add_link "$src" "$target"
}
# shellcheck disable=SC2153  # no misspelling
if [ -z "${FISH_COMPLETIONS+x}" ]; then
  ##### the following brace expansion is not supported in POSIX
  # "$target_folder"/{,auto}{complete,completion}{,s}{,/fish}/*.fish
  for file in \
    "$target_folder"/complete/*.fish             \
    "$target_folder"/complete/fish/*.fish        \
    "$target_folder"/completes/*.fish            \
    "$target_folder"/completes/fish/*.fish       \
    "$target_folder"/completion/*.fish           \
    "$target_folder"/completion/fish/*.fish      \
    "$target_folder"/completions/*.fish          \
    "$target_folder"/completions/fish/*.fish     \
    "$target_folder"/autocomplete/*.fish         \
    "$target_folder"/autocomplete/fish/*.fish    \
    "$target_folder"/autocompletes/*.fish        \
    "$target_folder"/autocompletes/fish/*.fish   \
    "$target_folder"/autocompletion/*.fish       \
    "$target_folder"/autocompletion/fish/*.fish  \
    "$target_folder"/autocompletions/*.fish      \
    "$target_folder"/autocompletions/fish/*.fish
  do
    link_fish_completion_file "$file"
  done
else
  for file in $FISH_COMPLETIONS; do
    link_fish_completion_file "$target_folder/$file"
  done
fi