#!/usr/bin/env sh


# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

set -e

if [ -d "$SHSH_INSTALL_ARCHPKG_ROOT" ]; then
    package="$1"

    # we want word splitting
    # shellcheck disable=SC2046
    remove_linked "$SHSH_PACKAGES_PATH/$package" $(find "$SHSH_INSTALL_ARCHPKG_ROOT/")
fi