#!/usr/bin/env sh

set -e

package="$1"

. "${UTILS_FUNC:?}"

echo_if_verbose "> Starting to link completions..."
if [ -e "$SHSH_PACKAGES_PATH/$package/package.sh" ]; then
  # shellcheck source=/dev/null
  . "$SHSH_PACKAGES_PATH/$package/package.sh"
fi

IFS=:
if [ -n "${BASH_COMPLETIONS:=}" ]; then
  mkdir -p "$SHSH_PREFIX/completions/bash"
  for completion in $BASH_COMPLETIONS; do
    ln -s "$SHSH_PACKAGES_PATH/$package/$completion" "$SHSH_PREFIX/completions/bash/${completion##*/}"
  done
fi

if [ -n "${ZSH_COMPLETIONS:=}" ]; then
  mkdir -p "$SHSH_PREFIX/completions/zsh/compsys"
  mkdir -p "$SHSH_PREFIX/completions/zsh/compctl"
  for completion in $ZSH_COMPLETIONS; do
    src="$SHSH_PACKAGES_PATH/$package/$completion"
    if grep -q "#compdef" "$src"; then
      target="$SHSH_PREFIX/completions/zsh/compsys/${completion##*/}"
    else
      target="$SHSH_PREFIX/completions/zsh/compctl/${completion##*/}"
    fi
    echo_if_verbose "Linking '$src' to '$target'"
    ln -s "$src" "$target"
  done
fi

link_fish_completion_file() {
  [ -e "$1" ] || [ -L "$1" ] || continue
  
  src="$1"
  target="$SHSH_PREFIX/completions/fish/"
  mkdir -p "$target"

  echo_if_verbose "Linking '$src' to '$target'"
  ln -s "$src" "$target"
}

if [ -n "${FISH_COMPLETIONS:=}" ]; then
  for file in $FISH_COMPLETIONS; do
    link_fish_completion_file "$file"
  done
else
  for file in "$SHSH_PACKAGES_PATH/$package"/completions/fish/*.fish "$SHSH_PACKAGES_PATH/$package"/completions/*.fish; do
    link_fish_completion_file "$file"
  done
fi