#!/usr/bin/env sh
#
# Summary: Clones a package from a site, but doesn't install it
#
# Usage: shsh _clone <use_ssh> <site> <package> <ref> <folder>

set -e
# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

if [ "$#" -ne 5 ]; then
  shsh help _clone
  exit 1
fi

use_ssh="$1"
site="$2"
package="$3"
ref="$4"
folder="$5"

if [ -z "$site" ] || [ -z "$package" ] || [ -z "$folder" ]; then
  shsh help _clone
  exit 1
fi

package_not_exists "$folder" || exit 1


if [ "$use_ssh" = "true" ]; then
  URI="git@$site:$package.git"
else
  URI="https://${site}/$package.git"
fi

[ -z "$SHSH_FULL_CLONE" ] && depth_option="--depth=1"

git clone ${depth_option:+"$depth_option"} ${ref:+--single-branch --branch "$ref"} ${SHSH_RECURSIVE_CLONE:+"--recursive"} "$URI" "${SHSH_PACKAGES_PATH}/$folder"
