#!/usr/bin/env bash
# Summary: Upgrades a package
# Usage: shsh upgrade <package|[-a/--all]> 

set -e

case $1 in
  -a|--all)
    upgrade_all="true"
    shift
  ;;
esac

if [ -n "$upgrade_all" ]; then
  echo "Checking packages status..."
  for package in $(shsh-outdated)
  do
    echo "Upgrading $package"
    shsh-upgrade "$package"
  done
  exit
fi

if [ "$#" -ne 1 ]; then
  shsh-help upgrade
  exit 1
fi

# TAG completions
if [ "$1" == "--complete" ]; then
  exec shsh-list
fi

package="$1"

if [ -z "$package" ]; then
  shsh-help upgrade
  exit 1
fi

IFS=/ read -r user name <<< "$package"

if [ -z "$user" ]; then
  shsh-help upgrade
  exit 1
fi

if [ -z "$name" ]; then
  shsh-help upgrade
  exit 1
fi

cd "${SHSH_PACKAGES_PATH}/$package"
git remote update > /dev/null 2>&1
if git symbolic-ref --short -q HEAD > /dev/null; then
    if [ "$(git rev-list --count HEAD...HEAD@{upstream})" -eq 0 ]; then
      # Exit when no need to upgrades. This also helps to avoid inf recursion even if
      # some package happened to set itself to be its own dependencies.
      exit
    fi
fi

# unlink everything first
shsh-_unlink-man "$package"
shsh-_unlink-bins "$package"
shsh-_unlink-completions "$package"
# upgrade the package
cd "${SHSH_PACKAGES_PATH}/$package"
git pull
# relink the package components
shsh-_link-bins "$package"
shsh-_link-man "$package"
shsh-_link-completions "$package"
# upgrade any dependencies it needs
for dep in $(shsh-_deps --get "$package")
do
  shsh-upgrade "$dep"
done
