#!/usr/bin/env sh

package="$1"

if [ -e "$SHSH_PACKAGES_PATH/$package/package.sh" ]; then
  # shellcheck source=/dev/null
  . "$SHSH_PACKAGES_PATH/$package/package.sh"
  bins=$(echo "${BINS:-}" | tr ':' '\n')
fi

if [ -z "$bins" ]; then
  if [ -e "$SHSH_PACKAGES_PATH/$package/bin" ]; then
    bins=$(ls -1 "$SHSH_PACKAGES_PATH/$package/bin/")
  else
    bins=$(find "$SHSH_PACKAGES_PATH/$package" -maxdepth 1 -mindepth 1 -perm -u+x -type f -or -type l)
  fi
fi

IFS='
'
for bin in $bins; do
  name="${bin##*/}"
  if ${REMOVE_EXTENSION:-false}; then
    name="${name%%.*}"
  fi
  mkdir -p "$SHSH_INSTALL_BIN"
  ln -s "$SHSH_PACKAGES_PATH/$package/$bin" "$SHSH_INSTALL_BIN/${name}"
  chmod +x "$SHSH_INSTALL_BIN/${name}"
done
