#!/usr/bin/env sh
# Summary: Configure the shell environment for shsh
# Usage: eval "$(shsh init SHELL)"
#
# SHELL: sh, bash, zsh, fish, etc.

# shellcheck disable=SC2016
set -e

if [ "$#" -ne 1 ]; then
  shsh-help init
  exit 1
fi

# TAG completions
if [ "$1" = "--complete" ]; then
  printf '%s\n' sh bash zsh fish
  exit
fi

shell="$1"

print_fish_commands() {
  echo 'set -gx SHSH_ROOT "'"$SHSH_ROOT"'"'
  # echo "$SHSH_PREFIX"

  # add to fish_user_path instead for better management
  # echo 'not contains $SHSH_INSTALL_BIN $fish_user_paths'
  if [ -d "$SHSH_JUNEST_BIN" ]; then
    # echo 'set -gx SHSH_JUNEST_BIN "'"$SHSH_JUNEST_BIN"'"'
    echo 'set -ax PATH '"$SHSH_JUNEST_BIN"
  fi
  echo 'contains '"$SHSH_INSTALL_BIN"' $PATH'
  echo 'or set -p PATH '"$SHSH_INSTALL_BIN"
  # echo 'or set -p fish_user_paths '"$SHSH_INSTALL_BIN"
}

print_sh_commands(){
  echo 'export SHSH_ROOT="'"$SHSH_ROOT"'"'

  if [ -d "$SHSH_JUNEST_BIN" ]; then
    # echo 'export SHSH_JUNEST_BIN="'"$SHSH_JUNEST_BIN"'"'
    echo 'export PATH="$PATH:'"$SHSH_JUNEST_BIN"'"'
  fi
  echo 'export PATH="'"$SHSH_INSTALL_BIN"':$PATH"'
}

load_bash_package_completions() {
  _folder="$SHSH_ROOT/cellar/completions"
  echo 'for f in $(command ls "'"$_folder"'/bash"); do source "'"$_folder"'/bash/$f"; done'

}

load_zsh_package_completions() {
  echo 'fpath=("'"$SHSH_ROOT"'/cellar/completions/zsh/compsys" $fpath)'
  echo 'for f in $(command ls "'"$SHSH_ROOT"'/cellar/completions/zsh/compctl"); do source "'"$SHSH_ROOT"'/cellar/completions/zsh/compctl/$f"; done'
}

# init variables and path for shsh
case "$shell" in
  fish )
    print_fish_commands
    ;;
  * )
    print_sh_commands
    ;;
esac

# init completions for shsh
if [ "$shell" != fish ]; then
  if [ -e "$SHSH_ROOT/lib/include.$shell" ]; then
    echo '. '"$SHSH_ROOT"'/lib/include.'"$shell"
  fi

  if [ -e "$SHSH_ROOT/completions/shsh.$shell" ]; then
    echo '. '"$SHSH_ROOT"'/completions/shsh.'"$shell"
  fi
  # completions for fish is loaded on-demand by completions path
fi

# init completions for packages
case "$shell" in
  bash )
    load_bash_package_completions
    ;;
  zsh )
    load_zsh_package_completions
    ;;
  fish )
    echo 'contains '"$SHSH_PREFIX"'/completions/fish $fish_complete_path'
    echo 'or set -p fish_complete_path '"$SHSH_PREFIX"'/completions/fish'
    ;;
esac
