#!/usr/bin/env bash
#
# Summary: List installed packages
# Usage: shsh list [-v]

set -e

case $1 in
  -v)
    verbose="true"
    shift
  ;;
esac

if [ "$#" -gt 0 ]; then
  shsh-help list
  exit 1
fi

shopt -s nullglob

for package_path in ${SHSH_PACKAGES_PATH}/*/*
do
  username="$(dirname "$package_path")"
  username="${username##*/}"
  package="${package_path##*/}"
  if [ -z "$verbose" ]; then
    echo "$username/$package"
  else
    printf "%-30s %-30s\n" "$username/$package" "($(git --git-dir=${SHSH_PACKAGES_PATH}/$username/$package/.git config --get remote.origin.url))"
  fi
done
