#!/usr/bin/env sh

set -e

package="$1"

. "${UTILS_FUNC:?}"

echo_if_verbose "> Starting to link bins..."
if [ -e "$SHSH_PACKAGES_PATH/$package/package.sh" ]; then
  # shellcheck source=/dev/null
  . "$SHSH_PACKAGES_PATH/$package/package.sh"
fi

# variable expansion with ${..+x} to all empty variables
# as user might want to NOT link anything by setting it as empty
# with --variable BIN=
[ -n "${BINS+x}" ] && bins=$(echo "${BINS:-}" | tr ':' '\n')

if [ -z "${bins+x}" ]; then
  list_all_executable() {
    cd "$1" && find "$2" -maxdepth 1 -mindepth 1 -perm -u+x -type f -or -type l
  }
  if [ -e "$SHSH_PACKAGES_PATH/$package/bin" ]; then
    bins=$(list_all_executable "$SHSH_PACKAGES_PATH/$package" bin)
  else
    # remove the "./" prefix with cut
    bins=$(list_all_executable "$SHSH_PACKAGES_PATH/$package" "." | cut -sd / -f 2-)
  fi
fi

mkdir -p "$SHSH_INSTALL_BIN"
IFS='
'
for bin in $bins; do
  name="${bin##*/}"
  if ${REMOVE_EXTENSION:-false}; then
    name="${name%%.*}"
  fi
  src="$SHSH_PACKAGES_PATH/$package/$bin"
  target="$SHSH_INSTALL_BIN/$name"
  
  add_link "$src" "$target"
  # chmod +x "$SHSH_INSTALL_BIN/$name"
done
