#!/usr/bin/env sh
#
# Usage: shsh _deps <package> [--get]
# Summary: Globally installs package runtime dependencies
#
# Installs the package dependencies, specified with the
# DEPS= variable on package.sh.
#
# Example: DEPS=username/repo1:otheruser/repo2

set -e

case $1 in
  --get)
    get_deps="true"
    shift
  ;;
esac

if [ "$#" -ne 1 ]; then
  shsh-help _deps
  exit 1
fi

package="$1"

if [ ! -e "$SHSH_PACKAGES_PATH/$package/package.sh" ]; then
  exit
fi
# shellcheck source=/dev/null
. "$SHSH_PACKAGES_PATH/$package/package.sh"

IFS=:
for dep in $DEPS; do
  # avoid globbing
  [ -e "$dep" ] || [ -L "$dep" ] || continue
  if [ -z "$get_deps" ]; then
    shsh-install "$dep"
  else
    echo "$dep"
  fi
done
