#!/usr/bin/env sh

set -e

# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

package="$1"
target_folder="$2"
ref="$3"

echo_if_verbose ">> Requesting github release info"
_response="$(request_gh_release_info "$package" "$ref")"

if [ "$(jq -r -n --argjson data "$_response" '$data.message')" = "Not Found" ]; then
  error_echo "> The given github repo '$package' was not found"
  exit 1
fi

echo_if_verbose ">> Saving release tag to file"
jq -n --argjson data "$_response" '$data' > "$target_folder/.gh-release_info"

# using EOF method as the original json might contain invalid characters
echo_if_verbose ">> Parsing json result"
all_available_assets="$(jq -n --argjson data "$_response" '$data.assets')"
available_assets="$all_available_assets"

ignored_file() {
  # This function will ignore the .gh-release_info file and the release asset's archive
  archive="$1"
  while IFS= read -r line; do
    case "$line" in
      */.gh-release_info) ;;
      */"$archive") ;;
      *)
        echo "$line"
        ;;
    esac
  done
}

#########################################
# auto-determine the target asset name
#########################################

auto_determine_assets() {
  available_assets="$1"
  for pref in $gh_release_asset x86_64 x86-64 amd64 linux64; do
    item="$(echo "$available_assets" | jq -r '.[] | select(.name|test("'"$pref"'"))')"
    if [ -n "$item" ]; then
      echo "$item"
    fi
  done
}

filter_by_preference() {
  # Filter out available options. If there are no more
  # canidates left after the filtering, revert back to
  # the original list
  # $1 jq array
  # $2 jq filter
  available_assets="$1"
  canidates="$( echo "$available_assets" | jq -r "$2" )"
  if [ -n "$(echo "$canidates" | jq 'select(length > 0)' )" ]; then
    # only replace when there are canidates left
    available_assets="$canidates"
  fi
  echo "$available_assets"
  echo_if_verbose ">> filtering with '$2'"
  echo_if_verbose ">>>> from '$(echo "$1" | jq -r '.[].name' | tr '\n' ' ')' to '$(echo "$available_assets" | jq -r '.[].name' | tr '\n' ' ')'"
}

# necessary condition
available_assets="$(auto_determine_assets "$available_assets")"
available_assets="$(echo "$available_assets" | jq -s '.' )"

# check results
if [ -z "$(echo "$available_assets" | jq 'select(length > 0)' )" ]; then
  printf "%s\n%s\n" ">> Unable to find suitable release asset. Available release assets are:" "$( echo "$all_available_assets" | jq -r '.[].name' )"
  exit 1
fi

##############################
# preferred condition
# archives
available_assets="$(filter_by_preference "$available_assets" 'map(select(.name|test("(.tgz)|(.tar.gz)|(.zip)|(.xz)$")))')"
# prefer statically linked assets
available_assets="$(filter_by_preference "$available_assets" 'map(select(.name|test("(linux-musl)|(linux)|(Linux)")))')"

# get first item
item="$(echo "$available_assets" | jq -r '.[0]')"

gh_release_asset="$(echo "$item" | jq -r '.name' | head -1)"

case "$gh_release_asset" in
  *.gz|*.xz)
    unarchive_cmd="tar xvf"
    ;;
  *.zip)
    unarchive_cmd="unzip"
    ;;
  *)
    # non-archive
    unarchive_cmd="echo"
    ;;
esac
echo ">> Going to download release asset '$gh_release_asset'"

# We don't want the nested variables to expand
# shellcheck disable=SC2016
_script='wget '"$(echo "$item" | jq -r '.browser_download_url' | head -1)"' && '$unarchive_cmd' "$gh_release_asset"'
execute_hooks "downloading gh-release" "$target_folder" "$_script"


# detect if the target folder contains exactly one entry and that entry is a directory
entry_paths=$(find "$target_folder" -mindepth 1 -maxdepth 1 | ignored_file "$gh_release_asset")
count=$(printf '%s\n' "$entry_paths" | wc -l)
# a gh-release will always have contains 2 entries:
# - the .gh-release_info file
# - the release asset's archive
# so we need to check for 3 => which means there's only 1 folder
SINGLE_DIR_COUNT=3
if [ "$count" -eq 1 ] && [ -d "$entry_paths" ]; then
  # only auto-set the root if the single directory isn't bin, completions, or man
  dir_name=$(basename "$entry_paths")
  case "$dir_name" in
    bin|completions|man)
      ;;
    *)
      echo ">> Auto-setting root directory to '$dir_name'"
      export ROOT="$dir_name"
      ;;
  esac
fi
