#!/usr/bin/env sh
# Summary: Uninstalls a package
# Usage: shsh uninstall <package>

set -e
# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

if [ "$#" -ne 1 ]; then
  shsh-help uninstall
  exit 1
fi

# TAG completions
if [ "$1" = "--complete" ]; then
  exec shsh-list
fi

package="$1"

if [ -z "$package" ]; then
  shsh-help uninstall
  exit 1
fi

IFS=/ read -r user name <<EOF
$package
EOF

if [ -z "$user" ]; then
  shsh-help uninstall
  exit 1
fi

if [ -z "$name" ]; then
  shsh-help uninstall
  exit 1
fi

if [ ! -d "$SHSH_PACKAGES_PATH/$package" ]; then
  echo "Package '$package' is not installed"
  exit 1
fi

shsh-_unlink-man "$package"
shsh-_unlink-bins "$package"
shsh-_unlink-completions "$package"
[ -n "$SHSH_HOOK_UNINSTALL" ] && execute_hooks "uninstall-hook" "$SHSH_PACKAGES_PATH/$package" "$SHSH_HOOK_UNINSTALL"

rm -rf "${SHSH_PACKAGES_PATH:?}/$package"
