#!/usr/bin/env sh
#
# Usage: shsh _deps <package> [--get]
# Summary: Globally installs package runtime dependencies
#
# Installs the package dependencies, specified with the
# DEPS= variable on package.sh.
#
# Example: DEPS=username/repo1:otheruser/repo2

set -e

for arg; do
  shift
  case "$arg" in
  --get)
    get_deps="true"
    ;;
  *)
    # set back any unused args
    set -- "$@" "$arg"
    ;;
  esac
done

if [ "$#" -ne 1 ]; then
  shsh-help _deps
  exit 1
fi

package="$1"

if [ -e "$SHSH_PACKAGES_PATH/$package/package.sh" ]; then
  # shellcheck source=/dev/null
  . "$SHSH_PACKAGES_PATH/$package/package.sh"
fi
[ -z "$DEPS" ] && exit

IFS=:
for dep in $DEPS; do
  if [ -z "$get_deps" ]; then
    shsh-install "$dep"
  else
    echo "$dep"
  fi
done
