#!/usr/bin/env sh
# Summary: Edits the auto-amending shshrc file with $EDITOR
# Usage: shsh edit

set -e
# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

if [ -z "$EDITOR" ]; then
  if command_exists nvim; then
    EDITOR="nvim"
  elif command_exists vim; then
    EDITOR="vim"
  elif command_exists nano; then
    EDITOR="nano"
  fi
fi

exec "$EDITOR" "$SHSHRC"
