#!/usr/bin/env sh

set -e

package="$1"

# man can be in package root or in a subdir named 'man'
for file in "$SHSH_PACKAGES_PATH/$package/"* "$SHSH_PACKAGES_PATH/$package"/man/*; do
  [ -e "$file" ] || [ -L "$file" ] || continue
  
  case "$file" in
    *.[1-9])
      # get the last digit
      n="${file##*[!0-9]}"
      mkdir -p "${SHSH_INSTALL_MAN}/man${n}"
      ln -s "$SHSH_PACKAGES_PATH/$package/man/$file" "$SHSH_INSTALL_MAN/man${n}/${file}"
      ;;
  esac
done
