#!/usr/bin/env sh

set -e

# remove_linked() {
#   if [[ "$(resolve_link $1)" = "$2/"* ]]; then
#     rm -f "$1"
#   fi
# }

package="$1"

for file in "$SHSH_INSTALL_MAN/man"*"/"*; do
  [ -e "$file" ] || [ -L "$file" ] || continue

  remove_linked "$file" "$SHSH_PACKAGES_PATH/$package"
done
