#!/usr/bin/env sh
#
# Summary: Clones a package from a site, but doesn't install it
#
# Usage: shsh _clone <use_ssh> <site> <package> [<ref>] [folder]

set -e

if [ "$#" -lt 3 ] && [ "$#" -gt 5 ]; then
  shsh-help _clone
  exit 1
fi

use_ssh="$1"
site="$2"
package="$3"
ref="$4"
folder="$5"

if [ -z "$site" ] || [ -z "$package" ] || [ -z "$folder" ]; then
  shsh-help _clone
  exit 1
fi

if [ -e "$SHSH_PACKAGES_PATH/$folder" ]; then
  echo "Package '$folder' is already present"
  exit 0
fi

if [ "$use_ssh" = "true" ]; then
  URI="git@$site:$package.git"
else
  URI="https://${site}/$package.git"
fi

git clone ${SHSH_FULL_CLONE:+"--depth=1"} ${ref:+"-b $ref"} --recursive "$URI" "${SHSH_PACKAGES_PATH}/$folder"
