#!/usr/bin/env sh
# Summary: Uninstalls a package
# Usage: shsh uninstall <package>
#   or:  shsh uninstall --use-rc [--noconfirm]
#
# Options:
#       --use-rc     uninstall all packages that is not present in SHSHRC file
#       --noconfirm  do not prompt to confirm uninstalling each package

set -e
# shellcheck source=libexec/shsh-_utils
. "${UTILS_FUNC:?}"

for arg; do
  shift
  case "$arg" in
  --use-rc|--rc)
    use_rc_file="true"
    ;;
  --noconfirm|--no-confirm)
    noconfirm="true"
    ;;
  -*)
    shsh-help uninstall
    exit 1
    ;;
  *)
    set -- "$@" "$arg"
    ;;
  esac
done

if [ "$#" -ne 1 ] && [ -z "$use_rc_file" ]; then
  shsh-help uninstall
  exit 1
fi

if [ -n "$use_rc_file" ] && [ "$#" -ne 0 ]; then
  shsh-help uninstall
  exit 1
fi

# using SHSHRC file
if [ -n "$use_rc_file" ]; then
  for _package in $(shsh list); do
    set +e
    shshrc_get_existing_install_cmd "$_package"
    set -e

    if [ -z "$existing" ]; then
      if [ -n "$noconfirm" ] || prompt "Uninstall $_package?"; then
        echo "> Uninstalling $_package"
        shsh uninstall "$_package"
      fi
    fi
  done
  exit
fi

# TAG completions
if [ "$1" = "--complete" ]; then
  exec shsh-list
fi

parse_install_folder "$1" && package="$_folder_full"
package_exists "$package" || exit 1
[ -z "$package" ] && exit 1

shsh-_unlink-man "$package"
shsh-_unlink-bins "$package"
shsh-_unlink-completions "$package"
[ -n "$SHSH_HOOK_UNINSTALL" ] && execute_hooks "uninstall-hook" "$SHSH_PACKAGES_PATH/$package" "$SHSH_HOOK_UNINSTALL"

rm -rf "${SHSH_PACKAGES_PATH:?}/$package"
