#!/usr/bin/env sh

set -e

package="$1"

. "${UTILS_FUNC:?}"

echo_if_verbose "> Starting to link man..."

link_mans() {
  file="$1"
  [ -e "$file" ] || [ -L "$file" ] || continue
  
  case "$file" in
    *.[1-9])
      # get the last digit
      n="${file##*[!0-9]}"
      manfile=$(basename "$file")
      mkdir -p "${SHSH_INSTALL_MAN}/man${n}"

      src="$file"
      target="$SHSH_INSTALL_MAN/man${n}/$manfile"
  
      echo_if_verbose "Linking '$src' to '$target'"
      ln -s "$src" "$target"
      ;;
  esac
}

if [ -n "${MANS:=}" ]; then
  IFS=:
  for file in $MANS; do
    link_mans "$file"
  done
else
  # man can be in package root or in a subdir named 'man'
  for file in "$SHSH_PACKAGES_PATH/$package"/man/man*/* "$SHSH_PACKAGES_PATH/$package"/man/* "$SHSH_PACKAGES_PATH/$package/"*; do
    link_mans "$file"
  done
fi
