#!/bin/sh

a="hi:ua"

# IFS=:

# for b in $a
# do
#   echo $b
# done

IFS=:
 for dep in $a; do

  echo "asd_ $dep _aa"
done


case "yadm.9" in
  *.[0-9])
    echo yes
    ;;
    esac


for f in * bin/*; do
  echo $f
done
